# Generated by Django 4.2.29 on 2026-04-08 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdocWebhookSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dependency', models.BooleanField(default=False, help_text='Opt in to prodoc.dependency.* webhook events (created, deleted, cascaded). Until set to True, the dispatcher in plane.prodoc.tasks falls back to the legacy Webhook.issue boolean for one release cycle (Extension 2 → Extension 3).')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('webhook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_settings', to='db.webhook')),
            ],
            options={
                'verbose_name': 'Prodoc Webhook Settings',
                'verbose_name_plural': 'Prodoc Webhook Settings',
                'db_table': 'prodoc_webhook_settings',
            },
        ),
    ]
