# Generated by Django 4.2.29 on 2026-04-08 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('holidays', models.JSONField(default=list, help_text="List of ISO date strings, e.g. ['2026-04-14', '2026-08-15'].")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_holiday_calendars', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Prodoc Holiday Calendar',
                'verbose_name_plural': 'Prodoc Holiday Calendars',
                'db_table': 'prodoc_holiday_calendars',
            },
        ),
        migrations.CreateModel(
            name='ProdocProjectSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('holiday_calendar', models.ForeignKey(blank=True, help_text="Optional per-project override. If null, the cascade resolver falls back to the workspace's first HolidayCalendar by name.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overriding_projects', to='prodoc.holidaycalendar')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_settings', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Prodoc Project Settings',
                'verbose_name_plural': 'Prodoc Project Settings',
                'db_table': 'prodoc_project_settings',
            },
        ),
        migrations.AddIndex(
            model_name='holidaycalendar',
            index=models.Index(fields=['workspace'], name='prodoc_holi_workspa_f939f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaycalendar',
            unique_together={('workspace', 'name')},
        ),
    ]
