# Generated by Django 4.2.29 on 2026-04-08 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0121_alter_estimate_type'),
        ('prodoc', '0002_holiday_and_project_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdocTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=120)),
                ('version', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Set True automatically on the first successful materialization. Locked templates reject PATCH; bump `version` to create a new row.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_templates', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Prodoc Template',
                'verbose_name_plural': 'Prodoc Templates',
                'db_table': 'prodoc_templates',
            },
        ),
        migrations.CreateModel(
            name='ProdocTemplateSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='prodoc.prodoctemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Prodoc Template Section',
                'verbose_name_plural': 'Prodoc Template Sections',
                'db_table': 'prodoc_template_sections',
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='prodoctemplate',
            index=models.Index(fields=['workspace', 'slug'], name='prodoc_temp_workspa_be9a73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prodoctemplate',
            unique_together={('workspace', 'slug', 'version')},
        ),
    ]
