# Generated by Django 4.2.29 on 2026-04-08 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodoc', '0003_template_and_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdocTemplateTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('offset_days', models.IntegerField(help_text='Working-day offset from the project start date.')),
                ('duration_days', models.IntegerField(help_text='Working-day duration of the task.')),
                ('role_key', models.CharField(max_length=50)),
                ('sla_hours', models.IntegerField(blank=True, null=True)),
                ('repeat_per_site', models.BooleanField(default=False)),
                ('repeat_per_wave', models.BooleanField(default=False)),
                ('dependency_mode', models.CharField(choices=[('all', 'all'), ('same_site', 'same_site')], default='all', max_length=20)),
                ('order', models.IntegerField()),
                ('migration_requirement_slugs', models.JSONField(default=list, help_text="List of ProdocMigrationRequirement slugs (workspace-scoped) to link to the materialized work items. Validated at materialize time against the workspace's requirement catalog.")),
                ('third_party_tool_slugs', models.JSONField(default=list, help_text='List of ProdocThirdPartyTool slugs (workspace-scoped) to link to the materialized work items.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prodoc.prodoctemplatesection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='prodoc.prodoctemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Prodoc Template Task',
                'verbose_name_plural': 'Prodoc Template Tasks',
                'db_table': 'prodoc_template_tasks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProdocTemplateTaskDependency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('downstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_deps', to='prodoc.prodoctemplatetask')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('upstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_deps', to='prodoc.prodoctemplatetask')),
            ],
            options={
                'verbose_name': 'Prodoc Template Task Dependency',
                'verbose_name_plural': 'Prodoc Template Task Dependencies',
                'db_table': 'prodoc_template_task_dependencies',
            },
        ),
        migrations.AddConstraint(
            model_name='prodoctemplatetaskdependency',
            constraint=models.CheckConstraint(check=models.Q(('upstream', models.F('downstream')), _negated=True), name='prodoc_tpl_task_dep_no_self'),
        ),
        migrations.AlterUniqueTogether(
            name='prodoctemplatetaskdependency',
            unique_together={('upstream', 'downstream')},
        ),
        migrations.AddIndex(
            model_name='prodoctemplatetask',
            index=models.Index(fields=['template', 'order'], name='prodoc_temp_templat_01ca41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prodoctemplatetask',
            unique_together={('template', 'slug')},
        ),
    ]
