# Generated by Django 4.2.29 on 2026-04-08 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodoc', '0004_template_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdocSite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_sites', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_sites', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Prodoc Site',
                'verbose_name_plural': 'Prodoc Sites',
                'db_table': 'prodoc_sites',
            },
        ),
        migrations.CreateModel(
            name='ProdocWave',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('start_offset_days', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('plane_module', models.ForeignKey(blank=True, help_text='Mirror Plane Module for this wave. Created by the wave POST endpoint (commit 9). SET_NULL on Module delete so the Wave row survives upstream Module lifecycle changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='db.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_waves', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_waves', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Prodoc Wave',
                'verbose_name_plural': 'Prodoc Waves',
                'db_table': 'prodoc_waves',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProdocWaveSite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_waves', to='prodoc.prodocsite')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_sites', to='prodoc.prodocwave')),
            ],
            options={
                'verbose_name': 'Prodoc Wave Site',
                'verbose_name_plural': 'Prodoc Wave Sites',
                'db_table': 'prodoc_wave_sites',
                'unique_together': {('wave', 'site')},
            },
        ),
        migrations.AddIndex(
            model_name='prodocwave',
            index=models.Index(fields=['workspace', 'project'], name='prodoc_wave_workspa_8e5a3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prodocwave',
            unique_together={('project', 'name'), ('project', 'order')},
        ),
        migrations.AddIndex(
            model_name='prodocsite',
            index=models.Index(fields=['workspace', 'project'], name='prodoc_site_workspa_d4d5f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prodocsite',
            unique_together={('project', 'code')},
        ),
    ]
