# Generated by Django 4.2.29 on 2026-04-08 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodoc', '0005_site_and_wave'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdocThirdPartyTool',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(help_text='Stable workspace-scoped handle referenced from template task `third_party_tool_slugs` JSON lists.', max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('crm', 'CRM'), ('analytics', 'Analytics'), ('communication', 'Communication'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=40)),
                ('default_owner_role', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_third_party_tools', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Prodoc Third-Party Tool',
                'verbose_name_plural': 'Prodoc Third-Party Tools',
                'db_table': 'prodoc_third_party_tools',
                'indexes': [models.Index(fields=['workspace', 'slug'], name='prodoc_thir_workspa_916d4a_idx')],
                'unique_together': {('workspace', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProdocMigrationRequirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(help_text='Stable workspace-scoped handle referenced from template task `migration_requirement_slugs` JSON lists. Required; the seed command and materializer both resolve by slug.', max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('data', 'Data Migration'), ('access', 'Access Provisioning'), ('compliance', 'Compliance / Legal'), ('integration', 'System Integration'), ('other', 'Other')], default='other', max_length=40)),
                ('default_owner_role', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_migration_requirements', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Prodoc Migration Requirement',
                'verbose_name_plural': 'Prodoc Migration Requirements',
                'db_table': 'prodoc_migration_requirements',
                'indexes': [models.Index(fields=['workspace', 'slug'], name='prodoc_migr_workspa_e67a10_idx')],
                'unique_together': {('workspace', 'slug')},
            },
        ),
    ]
