# Generated by Django 4.2.29 on 2026-04-08 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodoc', '0006_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdocMaterializationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('start_date', models.DateField()),
                ('error_log', models.TextField(blank=True, default='')),
                ('work_items_created', models.JSONField(default=list)),
                ('modules_created', models.JSONField(default=list)),
                ('relations_created', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_materialization_jobs', to='db.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materialization_jobs', to='prodoc.prodoctemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_materialization_jobs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Prodoc Materialization Job',
                'verbose_name_plural': 'Prodoc Materialization Jobs',
                'db_table': 'prodoc_materialization_jobs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project', 'status'], name='prodoc_mate_project_59562b_idx'), models.Index(fields=['workspace', 'status'], name='prodoc_mate_workspa_41deac_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProdocIssueLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sla_hours', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_link', to='db.issue')),
                ('migration_requirements', models.ManyToManyField(blank=True, related_name='linked_issues', to='prodoc.prodocmigrationrequirement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_issue_links', to='db.project')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_links', to='prodoc.prodocsite')),
                ('template_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_links', to='prodoc.prodoctemplatetask')),
                ('third_party_tools', models.ManyToManyField(blank=True, related_name='linked_issues', to='prodoc.prodocthirdpartytool')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('wave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_links', to='prodoc.prodocwave')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodoc_issue_links', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Prodoc Issue Link',
                'verbose_name_plural': 'Prodoc Issue Links',
                'db_table': 'prodoc_issue_links',
                'indexes': [models.Index(fields=['workspace', 'template_task'], name='prodoc_issu_workspa_a358cf_idx'), models.Index(fields=['workspace', 'site'], name='prodoc_issu_workspa_43a2ed_idx'), models.Index(fields=['workspace', 'wave'], name='prodoc_issu_workspa_0d62eb_idx')],
            },
        ),
    ]
